### ISSUE TITLE
 Error: Cannot find module './Commander.js'

### ISSUE THREAD

**Issue by ZR2** [Pyraxo/harubot#2]
Error: Cannot find module './Commander.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/dbb/lib/DiscordClient.js:7:19)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

**Comment by Pyraxo** [comment]
What command caused this error?

**Comment by Pyraxo** [comment]
I'm not sure what exactly causes this, it's fine on my end. Try reinstalling the bot again?
